export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_SEARCH_PRODUCTS_REQUEST = "GET_SEARCH_PRODUCTS_REQUEST";
export const GET_SEARCH_PRODUCTS_SUCCESS = "GET_SEARCH_PRODUCTS_SUCCESS";
export const GET_SEARCH_PRODUCTS_FAILURE = "GET_SEARCH_PRODUCTS_FAILURE";

export const GET_SEARCH_SORT_SUCCESS = "GET_SEARCH_SORT_SUCCESS";

export const GET_SEARCH_FILTER_SUCCESS = "GET_SEARCH_FILTER_SUCCESS";

export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
